"""State-teleportation protocol and app.

Implements standard quantum-state teleportation over a pre-shared Bell pair:
Alice Bell-measures her data qubit against her half of the pair and sends the
two classical bits; Bob applies the matching Pauli correction to his half.

This is the original teleport protocol (formerly
``entanglement_management.teleportation``) plus its :class:`TeleportApp`
(formerly ``app.teleport_app``), now expressed as a :class:`TeleportationProtocol`
registered under ``TELEPORT`` and grouped with its app.

NOTE: the teleport protocol is not generated by the Rule system; :class:`TeleportApp`
instantiates it per session. The protocol is asymmetric -- Alice and Bob differ.
"""

from enum import Enum, auto

from ..request_app import RequestApp
from ...components.circuit import Circuit
from ...message import Message
from ...utils import log
from ...constants import TELEPORT
from ...network_management.reservation import Reservation
from ...topology.node import DQCNode
from ...resource_management.memory_manager import MemoryInfo
from ...kernel.process import Process
from ...kernel.event import Event

from .teleportation_base import TeleportationProtocol


class TeleportMsgType(Enum):
    """Enumeration for different types of teleportation messages."""
    MEASUREMENT_RESULT = auto()  # Alice informs Bob of her measurement result
    ACK = auto()                 # Bob acknowledges Alice the teleportation is complete


class TeleportMessage(Message):
    """Classical message used to convey the Pauli corrections (x, z) from
    sender to receiver during teleportation.

    Attributes:
        reservation (Reservation): The reservation object associated with this teleportation message.
        bob_comm_memory_name (str): Name of the memory on Bob's side to be corrected.
        x_flip (int): MEASUREMENT_RESULT only, whether to apply X correction (1 for yes, 0 for no).
        z_flip (int): MEASUREMENT_RESULT only, whether to apply Z correction (1 for yes, 0 for no).
    """
    def __init__(self, msg_type: TeleportMsgType, **kwargs):
        super().__init__(msg_type, 'teleport_app')  # this app name must match what TeleportApp expects

        if msg_type is TeleportMsgType.MEASUREMENT_RESULT:
            self.reservation = kwargs['reservation']
            self.bob_comm_memory_name = kwargs['bob_comm_memory_name']
            self.x_flip = kwargs['x_flip']
            self.z_flip = kwargs['z_flip']
            self.string = f'type={TeleportMsgType.MEASUREMENT_RESULT}, bob_comm_memory={self.bob_comm_memory_name}, x_flip={self.x_flip}, z_flip={self.z_flip}, reservation={self.reservation}'

        elif msg_type is TeleportMsgType.ACK:
            self.reservation = kwargs['reservation']
            self.bob_comm_memory_name = kwargs['bob_comm_memory_name']
            self.string = f'type={TeleportMsgType.ACK}, bob_comm_memory={self.bob_comm_memory_name}, reservation={self.reservation}'

        else:
            raise Exception(f"TeleportMessage created with unknown message type: {msg_type}")

    def __str__(self):
        return self.string


@TeleportationProtocol.register(TELEPORT)
class TeleportProtocol(TeleportationProtocol):
    """Core teleportation logic:
     - alice_bell_measurement(): invoked when a comm-memory becomes ENTANGLED
     - bob_handle_correction(): invoked when Bob receives Alice's classical bits

    Attributes:
        owner (DQCNode): The node that owns this protocol.
        data_memory_index (int): The index of the data memory to teleport on Alice's side.
        alice (bool): Whether this protocol plays the Alice role.
        name (str): The name of the teleport protocol.
        remote_node_name (str): The name of the remote node (Bob) involved in the teleportation.
        alice_comm_memory_name (str): The name of the communication memory on Alice's side.
        alice_comm_memory (Memory): The communication memory on Alice's side.
        bob_comm_memory_name (str): The name of the communication memory on Bob's side.
        bob_comm_memory (Memory): The communication memory on Bob's side.
    """

    _bsm_circuit = Circuit(2)
    _bsm_circuit.cx(0, 1)
    _bsm_circuit.h(0)
    _bsm_circuit.measure(0)
    _bsm_circuit.measure(1)

    _z_flip_circuit = Circuit(1)
    _z_flip_circuit.z(0)

    _x_flip_circuit = Circuit(1)
    _x_flip_circuit.x(0)

    def __init__(self, owner: DQCNode, alice: bool = False, data_memory_index: int = None, remote_node_name: str = None):
        """ Initialize the teleportation protocol.

        Args:
            owner (DQCNode): The node that owns this protocol.
            alice (bool): Whether this protocol plays the Alice role.
            data_memory_index (int): The index of the data memory to teleport.
            remote_node_name (str): The name of the other node involved in the teleportation.
        """
        if alice:
            name = f"{owner.name}.teleport.{remote_node_name}.DataMemoryArray[{data_memory_index}]"
        else:
            name = f"{owner.name}.teleport.{remote_node_name}"
        super().__init__(owner, name, TELEPORT, alice=alice, remote_node_name=remote_node_name)
        self.data_memory_index = data_memory_index
        log.logger.debug(f"{self.name}: initialized (data_memory={data_memory_index})")

    def alice_bell_measurement(self, reservation: Reservation):
        """ Perform Bell measurement on the entangled memory and send corrections to Bob.
        """
        comm_key = self.alice_comm_memory.qstate_key
        data_memory_array = self.owner.get_component_by_name(self.owner.data_memo_arr_name)
        data_key = data_memory_array[self.data_memory_index].qstate_key
        log.logger.debug(f"{self.name}: alice_bell_measure data_key={data_key}, comm_key={comm_key}")
        # Perform Bell measurement
        rnd = self.owner.get_generator().random()
        meas = self.owner.timeline.quantum_manager.run_circuit(TeleportProtocol._bsm_circuit, [data_key, comm_key], rnd)
        z, x = meas[data_key], meas[comm_key]
        log.logger.info(f"{self.name} bell measurement results: x={x}, z={z}, remote memory={self.bob_comm_memory_name}")
        # send classical corrections to Bob
        msg = TeleportMessage(TeleportMsgType.MEASUREMENT_RESULT, bob_comm_memory_name=self.bob_comm_memory_name, x_flip=x, z_flip=z, reservation=reservation)
        self.owner.send_message(self.remote_node_name, msg)

    def received_message(self, src: str, msg: TeleportMessage):
        """ Handle incoming messages, specifically teleportation corrections.

        Args:
            src (str): Source of the message.
            msg (TeleportMessage): The teleportation message containing corrections.
        """
        if msg.msg_type == TeleportMsgType.MEASUREMENT_RESULT:
            self.bob_handle_correction(msg)
        else:
            log.logger.warning(f"{self.name}: received unknown message type {msg.type} from {src}")

    def bob_handle_correction(self, msg: TeleportMessage):
        """ Handle the classical correction message from Alice.
        Applies the corrections to the entangled memory and notifies the app.

        Args:
            msg (TeleportMessage): The message containing the correction bits.
        """
        log.logger.debug(f"{self.name}: bob_handle_correction, memory={msg.bob_comm_memory_name}, x_flip={msg.x_flip}, z_flip={msg.z_flip}")
        bob_comm_memory_key = self.bob_comm_memory.qstate_key

        if msg.x_flip:
            rnd = self.owner.get_generator().random()
            self.owner.timeline.quantum_manager.run_circuit(TeleportProtocol._x_flip_circuit, [bob_comm_memory_key], rnd)
            log.logger.info(f"{self.name}: X-flip applied on memory {msg.bob_comm_memory_name}")
        if msg.z_flip:
            rnd = self.owner.get_generator().random()
            self.owner.timeline.quantum_manager.run_circuit(TeleportProtocol._z_flip_circuit, [bob_comm_memory_key], rnd)
            log.logger.info(f"{self.name}: Z-flip applied on memory {msg.bob_comm_memory_name}")

        self.owner.teleport_app.teleport_complete(bob_comm_memory_key)

    def bob_acknowledge_complete(self, reservation: Reservation):
        """Acknowledge the completion of the teleportation process.

        Args:
            reservation (Reservation): The reservation object associated with the teleportation.
        """
        msg = TeleportMessage(TeleportMsgType.ACK, bob_comm_memory_name=self.bob_comm_memory_name, reservation=reservation)
        self.owner.send_message(self.remote_node_name, msg)
        log.logger.debug(f"{self.name}: sent ACK to {self.remote_node_name}")


class TeleportApp(RequestApp):
    """Code for the teleport application.

    TeleportApp is a specialized RequestApp that implements quantum teleportation.
    It handles the teleportation protocol between two quantum nodes (Alice and Bob).

    Attributes:
        node (DQCNode): The quantum node this app is attached to.
        name (str): The name of the teleport application.
        results (list): A list of results of (timestamp, teleported_state)
        teleport_protocols (list[TeleportProtocol]): A list of teleportation protocol instances.
    """
    def __init__(self, node: DQCNode):
        super().__init__(node)
        self.name = f"{self.node.name}.TeleportApp"
        node.teleport_app = self   # register ourselves so incoming TeleportMessage lands here:
        self.results = []          # where we'll collect Bob's teleported state
        self.teleport_protocols: list[TeleportProtocol] = []  # a list of teleport protocol instances
        log.logger.debug(f"{self.name}: initialized")

    def start(self, responder: str, start_t: int, end_t: int, memory_size: int, fidelity: float, data_memory_index: int):
        """Start the teleportation process.

        NOTE: only teleport one data memory qubit

        Args:
            responder (str): Name of the responder node (Bob).
            start_t (int): Start time of the teleportation (in ps).
            end_t (int): End time of the teleportation (in ps).
            memory_size (int): Size of the memory used for the teleportation.
            fidelity (float): Target fidelity of the teleportation.
            data_memory_index (int): Index of the data qubit to be teleported.
        """
        log.logger.debug(f"{self.name}: start() → responder={responder}, data_memory_index={data_memory_index}")

        # reserve and generate EPR pair
        super().start(responder, start_t, end_t, memory_size, fidelity)

        # init a new teleportation protocol for Alice only, and append to the list
        teleport_protocol = TeleportationProtocol.create(self.node, alice=True, data_memory_index=data_memory_index, remote_node_name=responder, protocol_type=TELEPORT)
        self.teleport_protocols.append(teleport_protocol)

    def get_reservation_result(self, reservation, result: bool):
        """Handle the reservation result from the network manager.

        Args:
            reservation (Reservation): The reservation object.
            result (bool): True if the reservation was successful, False otherwise.
        """
        super().get_reservation_result(reservation, result)
        log.logger.debug(f"{self.name}: reservation_result → {result}")

    def get_memory(self, info: MemoryInfo):
        """Handle memory state changes.

        Args:
            info (MemoryInfo): Information about the memory state change.
        """
        log.logger.debug(f"{self.name}: get_memory, name={info.memory.name}, state={info.state}")
        # once we see our entangled half, hand it to the protocol
        if info.index in self.memo_to_reservation:
            if info.state == "ENTANGLED":
                for teleport_protocol in self.teleport_protocols:
                    this_node = info.memory.owner.name
                    remote_node = info.remote_node
                    if this_node == teleport_protocol.owner.name and remote_node == teleport_protocol.remote_node_name:
                        # this node is Alice
                        teleport_protocol.set_alice_comm_memory_name(info.memory.name)
                        teleport_protocol.set_alice_comm_memory(info.memory)
                        teleport_protocol.set_bob_comm_memory_name(info.remote_memo)
                        reservation = self.memo_to_reservation[info.index]
                        # Let Bob first execute EntanglementGenerationA._entanglement_succeed(), then let Alice do the Bell measurement
                        time_now = self.node.timeline.now()
                        process = Process(teleport_protocol, 'alice_bell_measurement', [reservation])
                        priority = self.node.timeline.schedule_counter
                        event = Event(time_now, process, priority)
                        self.node.timeline.schedule(event)
                        break  # if no matching protocol found, go to else clause
                else:
                    # this node is Bob, create the new teleport protocol instance, then append to self.teleport_protocols
                    teleport_protocol = TeleportationProtocol.create(self.node, alice=False, remote_node_name=info.remote_node, protocol_type=TELEPORT)
                    teleport_protocol.set_bob_comm_memory_name(info.memory.name)
                    teleport_protocol.set_bob_comm_memory(info.memory)
                    teleport_protocol.set_alice_comm_memory_name(info.remote_memo)
                    self.teleport_protocols.append(teleport_protocol)

    def received_message(self, src: str, msg: TeleportMessage):
        """Handle incoming teleport messages.

        Args:
            src (str): Source node name.
            msg (TeleportMessage): The teleport message received.
        """
        log.logger.debug(f"{self.name} received_message from {src}: {msg}")
        if msg.msg_type is TeleportMsgType.MEASUREMENT_RESULT:  # Bob receives measurement result from Alice
            for teleport_protocol in self.teleport_protocols:   # find the correct teleport protocol on Bob's side
                if src == teleport_protocol.remote_node_name and msg.bob_comm_memory_name == teleport_protocol.bob_comm_memory_name:
                    teleport_protocol.received_message(src, msg)
                    self.node.resource_manager.expire_rules_by_reservation(msg.reservation)                    # early release of resources
                    self.node.resource_manager.update(None, teleport_protocol.bob_comm_memory, MemoryInfo.RAW)  # release the bob comm memory
                    teleport_protocol.bob_acknowledge_complete(msg.reservation)
                    self.teleport_protocols.remove(teleport_protocol)  # remove the protocol instance, it's lifecycle is complete
                    break
            else:
                log.logger.warning(f"{self.name}: received_message: no matching teleport protocol for msg={msg} from {src}")

        elif msg.msg_type is TeleportMsgType.ACK:              # Alice receives acknowledgment from Bob
            for teleport_protocol in self.teleport_protocols:  # find the correct teleport protocol on Alice's side
                if src == teleport_protocol.remote_node_name and msg.bob_comm_memory_name == teleport_protocol.bob_comm_memory_name:
                    self.node.resource_manager.expire_rules_by_reservation(msg.reservation)                      # expire the rules
                    self.node.resource_manager.update(None, teleport_protocol.alice_comm_memory, MemoryInfo.RAW)  # release the alice comm memory
                    self.teleport_protocols.remove(teleport_protocol)  # remove the protocol instance, it's lifecycle is complete
                    break
            else:
                log.logger.warning(f"{self.name}: received_message: no matching teleport protocol for msg={msg} from {src}")

    def teleport_complete(self, comm_key: int):
        """Called by TeleportProtocol once Bob's qubit is corrected. comm_key holds the teleported |ψ⟩.

        Args:
            comm_key (int): The key of the comm memory where the teleported state is stored.
        """
        my_qubit = self.node.timeline.quantum_manager.get(comm_key)
        psi = my_qubit.state  # get qubit state
        log.logger.info(f"{self.name}: teleport done, state={psi}")
        self.results.append((self.node.timeline.now(), psi))  # append result (timestamp, state)
