"""Base class and registry for teleportation-family protocols.

Teleportation protocols move quantum information across a pre-shared entangled
link via a local operation + classical communication. This package collects the
built-in variants under one registry, mirroring how
``entanglement_management.generation`` collects its generation protocols:

  * ``teleport`` -- standard state teleportation (Bell measure + Pauli correction).
  * ``teledata`` -- teleport a data qubit onto a remote comm memory, then SWAP it
    into the remote data memory.
  * ``telegate`` -- entanglement-assisted distributed (remote) CNOT gate.

Concrete protocols register under a name with ``@TeleportationProtocol.register``
and are created through the registry, exactly like ``EntanglementGenerationA``
and ``RoutingProtocol``. These protocols are asymmetric: the same class plays the
``alice`` (initiator) or ``bob`` (responder) role depending on the ``alice`` flag.

Unlike the generation module these live alongside their apps (in ``sequence.app``)
because, like the original teleport protocol, they are not generated by the Rule
system -- the owning app instantiates them per session.
"""

from __future__ import annotations

from abc import ABC
from typing import TYPE_CHECKING

from ...protocol import Protocol
from ...constants import TELEPORT

if TYPE_CHECKING:
    from ...topology.node import DQCNode
    from ...components.memory import Memory


class TeleportationProtocol(Protocol, ABC):
    """Abstract base class for teleportation-family protocols.

    Factors out the comm-memory bookkeeping shared by every variant (the
    Alice/Bob communication memories that hold the entangled pair) and provides
    the name-based registry used to select a variant.

    Class Attributes:
        _registry (dict[str, type['TeleportationProtocol']]): mapping of protocol
            names to their classes.
        _global_type (str): the globally selected protocol type used by
            :meth:`create` when no explicit ``protocol_type`` is given. Defaults
            to ``TELEPORT``.

    Instance Attributes:
        owner (DQCNode): node the protocol is attached to.
        name (str): name of this protocol instance.
        protocol_type (str): registered type of this protocol.
        alice (bool): whether this instance plays the Alice (initiator) role.
        remote_node_name (str): name of the remote node in this session.
        alice_comm_memory_name (str): name of Alice's communication memory.
        alice_comm_memory (Memory): Alice's communication memory object.
        bob_comm_memory_name (str): name of Bob's communication memory.
        bob_comm_memory (Memory): Bob's communication memory object.
    """

    _registry: dict[str, type['TeleportationProtocol']] = {}
    _global_type: str = TELEPORT

    def __init__(self, owner: "DQCNode", name: str, protocol_type: str,
                 alice: bool = False, remote_node_name: str = None):
        super().__init__(owner, name, protocol_type)
        self.alice = alice
        self.remote_node_name = remote_node_name

        # Filled in once the entangled pair is generated.
        self.alice_comm_memory_name: str = None
        self.alice_comm_memory: "Memory" = None
        self.bob_comm_memory_name: str = None
        self.bob_comm_memory: "Memory" = None

    # ---- registry -----------------------------------------------------------
    @classmethod
    def register(cls, name: str, protocol_class: type['TeleportationProtocol'] = None):
        """Register a teleportation protocol class under ``name``.

        Usable as a decorator (``@TeleportationProtocol.register(TELEPORT)``) or
        called directly with an explicit class.
        """
        if protocol_class is not None:
            cls._registry[name] = protocol_class
            return None

        def decorator(protocol_cls: type['TeleportationProtocol']):
            cls._registry[name] = protocol_cls
            return protocol_cls

        return decorator

    @classmethod
    def create(cls, *args, protocol_type: str = None, **kwargs) -> 'TeleportationProtocol':
        """Factory method to create a teleportation protocol instance.

        Args:
            protocol_type (str): name of the registered protocol to create. If
                ``None``, the globally selected type (:meth:`get_global_type`) is
                used. Positional/keyword args are forwarded to the protocol
                constructor (signatures differ per variant).

        Returns:
            TeleportationProtocol: the new protocol instance.
        """
        name = protocol_type if protocol_type is not None else cls.get_global_type()
        try:
            protocol_class = cls._registry[name]
        except KeyError:
            raise ValueError(f"Teleportation protocol '{name}' is not registered.")
        return protocol_class(*args, **kwargs)

    @classmethod
    def set_global_type(cls, protocol_type: str) -> None:
        if protocol_type not in cls._registry:
            raise ValueError(f"Teleportation protocol '{protocol_type}' is not registered.")
        cls._global_type = protocol_type

    @classmethod
    def get_global_type(cls) -> str:
        return cls._global_type

    @classmethod
    def clear_global(cls) -> None:
        cls._global_type = TELEPORT

    @classmethod
    def list_protocols(cls) -> list[str]:
        """List all registered teleportation protocol names."""
        return list(cls._registry.keys())

    # ---- shared comm-memory setters ----------------------------------------
    def set_alice_comm_memory_name(self, memory_name: str) -> None:
        """Set the name of Alice's communication memory."""
        self.alice_comm_memory_name = memory_name

    def set_alice_comm_memory(self, memory: "Memory") -> None:
        """Set Alice's communication memory object."""
        self.alice_comm_memory = memory

    def set_bob_comm_memory_name(self, memory_name: str) -> None:
        """Set the name of Bob's communication memory."""
        self.bob_comm_memory_name = memory_name

    def set_bob_comm_memory(self, memory: "Memory") -> None:
        """Set Bob's communication memory object."""
        self.bob_comm_memory = memory
